"""Add Users and Role tables

Revision ID: 149846c75a1f
Revises: 
Create Date: 2022-11-14 13:36:37.503925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149846c75a1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_table('users_pat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('data_day', sa.Integer(), nullable=False),
    sa.Column('data_month', sa.Integer(), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=False),
    sa.Column('home_address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_pat'))
    )
    op.create_table('users_med',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_med_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_med')),
    sa.UniqueConstraint('login', name=op.f('uq_users_med_login'))
    )
    op.create_table('med_patient',
    sa.Column('med_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['med_id'], ['users_med.id'], name=op.f('fk_med_patient_med_id_users_med')),
    sa.ForeignKeyConstraint(['patient_id'], ['users_pat.id'], name=op.f('fk_med_patient_patient_id_users_pat')),
    sa.PrimaryKeyConstraint('med_id', 'patient_id', name=op.f('pk_med_patient'))
    )
    data_upgrades()
    # ### end Alembic commands ###

def data_upgrades():
    table = sa.sql.table('roles', sa.sql.column('name', sa.String))

    op.bulk_insert(table,
        [
            { 'name': 'Администратор' },
            { 'name': 'Пользователь' },
        ]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('med_patient')
    op.drop_table('users_med')
    op.drop_table('users_pat')
    op.drop_table('roles')
    # ### end Alembic commands ###
